# Generated by Django 3.2.16 on 2023-02-08 08:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название курса')),
                ('code', models.CharField(max_length=255, verbose_name='Код')),
            ],
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИ')),
                ('prof', models.CharField(max_length=255, verbose_name='Должность')),
            ],
        ),
        migrations.CreateModel(
            name='EduLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255, verbose_name='Уровень обучения')),
            ],
        ),
        migrations.CreateModel(
            name='Format',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255, verbose_name='формат')),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Язык')),
            ],
        ),
        migrations.CreateModel(
            name='Proficiency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=255, verbose_name='Знание языка')),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название школы')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255, verbose_name='Статус')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='full_name',
            field=models.CharField(max_length=255, null=True, verbose_name='ФИ'),
        ),
        migrations.AddField(
            model_name='user',
            name='prof',
            field=models.CharField(default='Лектор', max_length=255, verbose_name='Должность'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Syllabus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('syllabus_name', models.CharField(max_length=255, verbose_name='Название силлабуса')),
                ('total_hours', models.IntegerField(null=True, verbose_name='Всего часов')),
                ('classroom_hours', models.IntegerField(null=True, verbose_name='Классных часов')),
                ('iw_hours', models.IntegerField(null=True, verbose_name='СРОП часов')),
                ('prerequisites', models.BooleanField(null=True, verbose_name='Пререквизиты')),
                ('time_place', models.CharField(max_length=255, verbose_name='Время и место проведения')),
                ('course_objective', models.CharField(max_length=255, verbose_name='Цель курса')),
                ('document', models.FileField(null=True, upload_to='', verbose_name='Файл')),
                ('agreed_with', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.director')),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.course')),
                ('format_of_training', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.format')),
                ('instructor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('language_of_education', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.language')),
                ('proficiency_level', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.proficiency')),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.status')),
                ('training_level', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.edulevel')),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.IntegerField(null=True, verbose_name='Неделя')),
                ('theme', models.CharField(max_length=255, verbose_name='Тема')),
                ('tasks', models.CharField(max_length=255, verbose_name='Задания')),
                ('format', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.format')),
                ('syllabus', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.syllabus')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.school'),
        ),
    ]
